version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chat-free-easy-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Variables de entorno para NextAuth.js
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      # URL del backend WebSocket
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-ws://localhost:4000}
    restart: unless-stopped
    networks:
      - chat-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat-free-easy-backend
    ports:
      - "4000:4000"
    restart: unless-stopped 
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
